# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 19:26
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComingSoon',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='themes_comingsoon', serialize=False, to='cms.CMSPlugin')),
                ('email', models.EmailField(max_length=254)),
                ('page_heading', models.CharField(max_length=128)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='First line text', null=True, verbose_name='First Line Text')),
                ('date', models.DateField(default=datetime.date(2017, 9, 7))),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
