# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-05 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_auto_20170904_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comingsoon',
            name='date',
            field=models.DateField(default=datetime.date(2017, 9, 5)),
        ),
    ]
