# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-05 13:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0006_auto_20170905_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comingsoon',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 13, 31, 40, 839610, tzinfo=utc)),
        ),
    ]
