# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-05 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0007_auto_20170905_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comingsoon',
            name='date',
        ),
    ]
