# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 11:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('telephone', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('project_summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('location', models.CharField(max_length=128)),
                ('start_implementation', models.DateField(blank=True, null=True)),
                ('end_implementation', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, help_text='Use numbers <small>e.g</small> 1, 2 or 3', null=True)),
                ('question', models.CharField(blank=True, max_length=128, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_question', to='stick2uganda.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, help_text='Use numbers <small>e.g</small> A or B', max_length=128, null=True)),
                ('completed', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_report', to='stick2uganda.Project')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='stick2uganda.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Stick2UgandaPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='stick2uganda_stick2ugandaplugin', serialize=False, to='cms.CMSPlugin')),
                ('info', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('intro_small', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_contact', to='stick2uganda.Project'),
        ),
    ]
