# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('telephone', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('start_implementation', models.DateField(blank=True, null=True)),
                ('end_implementation', models.DateField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stick2uganda.ContactPerson')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, help_text='Use numbers <small>e.g</small> 1, 2 or 3', null=True)),
                ('question', models.CharField(blank=True, max_length=128, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, help_text='Use numbers <small>e.g</small> A or B', max_length=128, null=True)),
                ('completed', models.DateField(blank=True, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stick2uganda.Question')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stick2uganda.Report'),
        ),
    ]
