# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stick2uganda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('can_add_question', 'Can add Question'), ('can_edit_question', 'Can edit Question'))},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('can_add_report', 'Can add Rreport'), ('can_edit_report', 'Can edit Report'))},
        ),
    ]
