# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stick2uganda', '0002_remove_report_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stick2uganda.Project'),
        ),
    ]
