# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 07:34
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stick2uganda', '0002_auto_20170907_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='findings',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
