# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-05 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('stick2uganda', '0003_question_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stick2UgandaPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='stick2uganda_stick2ugandaplugin', serialize=False, to='cms.CMSPlugin')),
                ('stick2uganda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stick2uganda.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
