# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-22 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stick2uganda', '0004_s2uimageplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='s2uimageplugin',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
