# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-22 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stick2uganda', '0007_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, max_length=128000, null=True, upload_to='/project'),
        ),
    ]
