# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-05 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stick2uganda', '0007_auto_20170905_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='stick2uganda.ContactPerson'),
        ),
        migrations.AlterField(
            model_name='project',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stick2uganda.Report'),
        ),
    ]
