# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stick2uganda', '0008_auto_20170905_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='stick2uganda.Project'),
        ),
        migrations.AlterField(
            model_name='report',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='stick2uganda.Question'),
        ),
    ]
