# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stick2uganda', '0009_auto_20170906_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='project',
            name='report',
        ),
        migrations.RemoveField(
            model_name='stick2ugandaplugin',
            name='stick2uganda',
        ),
        migrations.AddField(
            model_name='contactperson',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_contact', to='stick2uganda.Project'),
        ),
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_report', to='stick2uganda.Project'),
        ),
        migrations.AlterField(
            model_name='question',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_question', to='stick2uganda.Project'),
        ),
    ]
