# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 14:03
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('stick2uganda', '0009_auto_20170924_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='add_findings_placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='add_findings', to='cms.Placeholder'),
        ),
    ]
