# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 09:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stick2uganda', '0010_question_add_findings_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='findings',
            field=ckeditor.fields.RichTextField(blank=True, default='Fill Your Report Here)', null=True),
        ),
    ]
